# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name:"Harold", last_name:"Müller", email:"hlmuller@uc.cl", password:"123456", role:2)

User.create(first_name:"Joaquin", last_name:"Castillo", email:"jacastillo@uc.cl", password:"Joaquin", role:1)

User.create(first_name:"Normal", last_name:"User", email:"normal@uc.cl", password:"123456", role:1)

User.create(first_name:"RecibeMail", last_name:"User", email:"joaquincastillosilva@gmail.com", password:"123456", role:1)


Gender.create(gender:"Sci-Fi")
Gender.create(gender:"Drama")
Gender.create(gender:"Action")
Gender.create(gender:"Suspense")
Gender.create(gender:"Thriller")
Gender.create(gender:"Terror")
Gender.create(gender:"Comedy")
Gender.create(gender:"Fantasy")
Gender.create(gender:"Musical")
Gender.create(gender:"Other")

Director.create(first_name: "Other", last_name: "")
Director.create(first_name: "Aan", last_name: "Levi")
Director.create(first_name: "Aaron", last_name: "Blaise")
Director.create(first_name: "Abbas", last_name: "Alibhai")
Director.create(first_name: "Abdel", last_name: "Kechiche")
Director.create(first_name: "Abdelatif", last_name: "HWidar")
Director.create(first_name: "Abel", last_name: "Ferrada")
Director.create(first_name: "Barnaby", last_name: "Thompson")
Director.create(first_name: "Barnie", last_name: "Elliot")
Director.create(first_name: "Barry", last_name: "Cook")
Director.create(first_name: "Camille", last_name: "Thomasson")
Director.create(first_name: "Camillo", last_name: "Mastrocinque")
Director.create(first_name: "Can", last_name: "Evrenol")
Director.create(first_name: "Candela", last_name: "Figueira")
Director.create(first_name: "Cao", last_name: "Hamburger")
Director.create(first_name: "Carl", last_name: "Boese")
Director.create(first_name: "Damian", last_name: "Lee")
Director.create(first_name: "David", last_name: "Bennioff")
Director.create(first_name: "Ed", last_name: "Solomon")
Director.create(first_name: "Eddie", last_name: "Arno")
Director.create(first_name: "Edgar", last_name: "Neville")
Director.create(first_name: "Fabio", last_name: "Barreto")
Director.create(first_name: "Fabrizio", last_name: "Costa")
Director.create(first_name: "Fausto", last_name: "Brizzi")
Director.create(first_name: "Gabriel", last_name: "Byrne")
Director.create(first_name: "Gabriela", last_name: "Pichler")
Director.create(first_name: "Hal", last_name: "Walker")
Director.create(first_name: "Hannes", last_name: "Holm")
Director.create(first_name: "Ian", last_name: "Gilmour")
Director.create(first_name: "Ib", last_name: "Meichior")
Director.create(first_name: "Ida", last_name: "Lupino")
Director.create(first_name: "J. Lee", last_name: "Thompson")
Director.create(first_name: "J.J", last_name: "Abrams")
Director.create(first_name: "Jacinto", last_name: "Molina")
Director.create(first_name: "Karim", last_name: "Dridi")
Director.create(first_name: "Karime", last_name: "Fernandez")
Director.create(first_name: "Karl", last_name: "Geurs")
Director.create(first_name: "Lamberto", last_name: "Lambertini")
Director.create(first_name: "Lara", last_name: "Shapiro")
Director.create(first_name: "Larry", last_name: "Buchanan")
Director.create(first_name: "Malcolm", last_name: "Clarke")
Director.create(first_name: "Nagisa", last_name: "Oshima")
Director.create(first_name: "Nancy", last_name: "Meyers")
Director.create(first_name: "Oliva", last_name: "Acosta")
Director.create(first_name: "Oliver", last_name: "Stone")
Director.create(first_name: "Olivier", last_name: "Baraoux")
Director.create(first_name: "Pablo", last_name: "Larrain")
Director.create(first_name: "Q. Allan", last_name: "Brocka")
Director.create(first_name: "Quentin", last_name: "Tarantino")
Director.create(first_name: "Rachel", last_name: "Samuels")
Director.create(first_name: "Rafa", last_name: "Cortes")
Director.create(first_name: "Rafael", last_name: "Alcazar")
Director.create(first_name: "Sabine", last_name: "Bernardi")
Director.create(first_name: "Sam", last_name: "Fell")
Director.create(first_name: "Takashi", last_name: "Miike")
Director.create(first_name: "Tania", last_name: "Hermida")
Director.create(first_name: "Tanya", last_name: "Fenmore")
Director.create(first_name: "Uberto", last_name: "Pasolini")
Director.create(first_name: "ULu", last_name: "Grosbard")
Director.create(first_name: "Uwe", last_name: "Boll")
Director.create(first_name: "Val", last_name: "Guest")
Director.create(first_name: "Valeria", last_name: "Sarmiento")
Director.create(first_name: "Veit", last_name: "Helmer")
Director.create(first_name: "Wally", last_name: "Pfister")
Director.create(first_name: "Walter", last_name: "Hill")
Director.create(first_name: "Xavier", last_name: "Koller")
Director.create(first_name: "Xiao", last_name: "Jiang")
Director.create(first_name: "Yael", last_name: "Russcol")
Director.create(first_name: "Yared", last_name: "Zeleke")
Director.create(first_name: "Yim", last_name: "Ho")
Director.create(first_name: "Zach", last_name: "Braff")
Director.create(first_name: "Zhixing", last_name: "Zhong")
